# Generated by Django 6.0.7 on 2026-07-10 09:25

import django.db.models.deletion
import django.db.models.expressions
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('label_id', models.CharField(max_length=60, verbose_name='Indonesian label')),
                ('phase', models.CharField(max_length=20)),
                ('is_sailing', models.BooleanField(default=False)),
                ('sort_hint', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['sort_hint'],
            },
        ),
        migrations.CreateModel(
            name='Charterer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Jetty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('port', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name_plural': 'jetties',
            },
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('tug_name', models.CharField(max_length=60)),
                ('barge_name', models.CharField(max_length=60)),
                ('capacity_mt', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCharterer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical charterer',
                'verbose_name_plural': 'historical charterers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalJetty',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('port', models.CharField(blank=True, max_length=80)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical jetty',
                'verbose_name_plural': 'historical jetties',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVessel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('tug_name', models.CharField(max_length=60)),
                ('barge_name', models.CharField(max_length=60)),
                ('capacity_mt', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vessel',
                'verbose_name_plural': 'historical vessels',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVoyage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('contract_no', models.CharField(blank=True, max_length=60)),
                ('invoice_no', models.CharField(blank=True, max_length=60)),
                ('laytime_days', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('laytime_load_days', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('laytime_discharge_days', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('demurrage_rate_idr', models.BigIntegerField(blank=True, null=True)),
                ('freight_idr', models.BigIntegerField(blank=True, null=True)),
                ('fuel_used_liters', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('ONGOING', 'Berjalan'), ('COMPLETED', 'Selesai')], default='ONGOING', max_length=10)),
                ('locked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('charterer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='voyages.charterer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('discharge_jetty', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='voyages.jetty')),
                ('vessel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='voyages.vessel')),
            ],
            options={
                'verbose_name': 'historical voyage',
                'verbose_name_plural': 'historical voyages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('contract_no', models.CharField(blank=True, max_length=60)),
                ('invoice_no', models.CharField(blank=True, max_length=60)),
                ('laytime_days', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('laytime_load_days', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('laytime_discharge_days', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('demurrage_rate_idr', models.BigIntegerField(blank=True, null=True)),
                ('freight_idr', models.BigIntegerField(blank=True, null=True)),
                ('fuel_used_liters', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('ONGOING', 'Berjalan'), ('COMPLETED', 'Selesai')], default='ONGOING', max_length=10)),
                ('locked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('charterer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voyages', to='voyages.charterer')),
                ('discharge_jetty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discharging_voyages', to='voyages.jetty')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voyages', to='voyages.vessel')),
            ],
            options={
                'ordering': ['vessel', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(default='CPO', max_length=40)),
                ('quantity_mt', models.DecimalField(decimal_places=3, max_digits=10)),
                ('shipper', models.CharField(blank=True, max_length=120)),
                ('load_jetty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loaded_parcels', to='voyages.jetty')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='voyages.voyage')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalVoyageCost',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('category', models.CharField(choices=[('STEVEDORING', 'Stevedoring'), ('PORT_CHARGES', 'Biaya pelabuhan'), ('AGENCY', 'Agen'), ('BUNKER', 'Bunker'), ('OTHER', 'Lainnya')], max_length=20)),
                ('amount_idr', models.BigIntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('incurred_on', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='voyages.voyage')),
            ],
            options={
                'verbose_name': 'historical voyage cost',
                'verbose_name_plural': 'historical voyage costs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalParcel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('commodity', models.CharField(default='CPO', max_length=40)),
                ('quantity_mt', models.DecimalField(decimal_places=3, max_digits=10)),
                ('shipper', models.CharField(blank=True, max_length=120)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('load_jetty', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='voyages.jetty')),
                ('voyage', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='voyages.voyage')),
            ],
            options={
                'verbose_name': 'historical parcel',
                'verbose_name_plural': 'historical parcels',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalActivity',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('from_location', models.CharField(blank=True, max_length=120)),
                ('to_location', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('activity_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='voyages.activitytype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='voyages.voyage')),
            ],
            options={
                'verbose_name': 'historical activity',
                'verbose_name_plural': 'historical activities',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('from_location', models.CharField(blank=True, max_length=120)),
                ('to_location', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='voyages.activitytype')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='voyages.voyage')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='VoyageCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('STEVEDORING', 'Stevedoring'), ('PORT_CHARGES', 'Biaya pelabuhan'), ('AGENCY', 'Agen'), ('BUNKER', 'Bunker'), ('OTHER', 'Lainnya')], max_length=20)),
                ('amount_idr', models.BigIntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('incurred_on', models.DateField(blank=True, null=True)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='voyages.voyage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='voyage',
            constraint=models.UniqueConstraint(fields=('vessel', 'code'), name='voyage_code_unique_per_vessel'),
        ),
        migrations.AddConstraint(
            model_name='voyage',
            constraint=models.CheckConstraint(condition=models.Q(('laytime_days__isnull', True), ('laytime_load_days__isnull', True), ('laytime_discharge_days__isnull', True), ('laytime_days', django.db.models.expressions.CombinedExpression(models.F('laytime_load_days'), '+', models.F('laytime_discharge_days'))), _connector='OR'), name='voyage_split_laytime_sums'),
        ),
        migrations.AddConstraint(
            model_name='parcel',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_mt__gt', 0)), name='parcel_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__isnull', True), ('end_at__gte', models.F('start_at')), _connector='OR'), name='activity_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='voyagecost',
            constraint=models.CheckConstraint(condition=models.Q(('amount_idr__gte', 0)), name='voyage_cost_not_negative'),
        ),
    ]
